<?php

namespace AppBundle\Repository;

/**
 * FeetbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeetbackRepository extends \Doctrine\ORM\EntityRepository
{
}
